-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aviones
(
    id_avion bigint NOT NULL,
    modelo text COLLATE pg_catalog."default",
    peso bigint,
    capacidad bigint,
    id_piloto bigint,
    id_hangares bigint,
    CONSTRAINT aviones_pkey PRIMARY KEY (id_avion)
);

CREATE TABLE IF NOT EXISTS public.hangares
(
    id_hangares bigint NOT NULL,
    capacidad bigint,
    localizacion text COLLATE pg_catalog."default",
    CONSTRAINT hangares_pkey PRIMARY KEY (id_hangares)
);

CREATE TABLE IF NOT EXISTS public.piloto
(
    id_piloto bigint NOT NULL,
    restricciones text COLLATE pg_catalog."default",
    salario bigint,
    turno text COLLATE pg_catalog."default",
    CONSTRAINT piloto_pkey PRIMARY KEY (id_piloto)
);

ALTER TABLE IF EXISTS public.aviones
    ADD CONSTRAINT id_hangares FOREIGN KEY (id_hangares)
    REFERENCES public.hangares (id_hangares) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.aviones
    ADD CONSTRAINT id_piloto FOREIGN KEY (id_piloto)
    REFERENCES public.piloto (id_piloto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;